//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomDimaDen.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Группы
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Группы()
        {
            this.Студенты = new HashSet<Студенты>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ID_Специальности { get; set; }
        public Nullable<int> Количество_студентов_в_группе { get; set; }
        public Nullable<int> Количество_свободных_мест_в_группе { get; set; }
        public string Префикс_группы { get; set; }
        public Nullable<int> Курс { get; set; }
        public Nullable<System.DateTime> Дата_формирования { get; set; }
        public Nullable<System.DateTime> Дата_окончания_обучения { get; set; }
        public Nullable<int> ID_Преподаватель { get; set; }
    
        public virtual Преподаватель Преподаватель { get; set; }
        public virtual Специальности Специальности { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Студенты> Студенты { get; set; }
    }
}
