//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomDimaDen.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Заявки
    {
        public int ID { get; set; }
        public string ФИО { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public string Место_обучения { get; set; }
        public string Аттестат { get; set; }
        public string Номер_телефона { get; set; }
        public string Эл_почта { get; set; }
        public Nullable<int> ID_Статус_заявки { get; set; }
        public Nullable<int> ID_Специальности { get; set; }
    
        public virtual Специальности Специальности { get; set; }
        public virtual Статус_заявки Статус_заявки { get; set; }
    }
}
